### ISSUE TITLE
[MENFORCER-364] requireFilesExist rule should be case sensitive

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-enforcer#477]
**[Johannes Goebel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=appreciated)** opened **[MENFORCER-364](https://issues.apache.org/jira/browse/MENFORCER-364?redirect=false)** and commented

When using the enforcer plugin with a configuration using the `requireFilesExist` rule, as follows, the case of the existence of files cannot be enforced case sensitive.

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-enforcer-plugin</artifactId>
    <version>3.0.0-M3</version>
    <executions>
        <execution>
            <id>enforce-files-exist</id>
            <goals>
                <goal>enforce</goal>
            </goals>
            <configuration>
                <rules>
                    <requireFilesExist>
                        <files>
                            <file>src/main/resources/i18n_de.properties</file>
                        </files>
                    </requireFilesExist>
                </rules>
                <fail>true</fail>
            </configuration>
        </execution>
    </executions>
</plugin>
```

For example, if the file `src/main/resources/i18n_DE.properties` exists, but not `src/main/resources/i18n_de.properties` the execution of the plugin will succeed.
Unfortunately in my use case, this is exactly the requirement. I have not found a way to enforce case sensitivity for this rule.

---

**Affects:** 3.0.0-M3

0 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Can you state on which OS this has happened?

**Comment by jira-importer** [comment]
**[Johannes Goebel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=appreciated)** commented

Sorry I missed that, the OS is Windows 10.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Interesting, did `ResourceBundle` load the incorrectly named file on Windows actually?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [335f26e39d1f20e157c46485481e36f858135a14](https://gitbox.apache.org/repos/asf?p=maven-enforcer.git;a=commit;h=335f26e39d1f20e157c46485481e36f858135a14)
I've decided to make it the expected behavior, so no configuration.
Configuration would only make sense if the project would only be build on case insensitive OSes like Windows, for ever. I don't think that is realistic.

**Comment by jira-importer** [comment]
**[Gene Smith](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gene)** commented

The change can break the test for paths with ".." or "." in them.:
* C:\hello\..\world\
* C:\some\path\workspace\code-project\..\resource-project\blah\
* ${basedir}\..\resource-project\

Whether or not it does seems to depend on maven versions and other things.

I don't love the paths, but a project support uses them.   I will probably work around it
for my projects by writing a custom rule, rather than wait for a fix.

...

And it would have saved me an hour if the log said it was a case sensitivity match that failed.
I had to dig into the source code of the plugin to figure out why it was saying a path did not
exist when I could see and test the file.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

[Gene Smith](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gene) To me these are all possible to fix within the existing rule. Please create a new ticket for it.

**Comment by jira-importer** [comment]
**[Torbjörn Svensson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER299344)** commented

The change in [335f26e39d1f20e157c46485481e36f858135a14](https://gitbox.apache.org/repos/asf?p=maven-enforcer.git;a=commit;h=335f26e39d1f20e157c46485481e36f858135a14) causes a regression when the file that is to be checked is a symbolic link.

In the case of a symbolic link, the java.io.File#getCanonicalFile() returns the fully resolved java.io.File object containing the target of the symbolic link and not the link itself.

**Comment by jira-importer** [comment]
**[Jason](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bigj)** commented

[st-torbjornsvensson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=st-torbjornsvensson) - MENFORCER-390 covers the symbolic link regression.

**Comment by jemischi** [comment]
@Johannes Goebel:

If you really need to distinguish the case of filenames on NTFS (i assume you are working in an NTFS partition),
you can activate case-sensitivity for a certain directory, by running following command in an admin shell:

`fsutil file setCaseSensitiveInfo "c:\path\to\folder" enable`

Then java.io.File.exists() will properly distinguish between uppercase and lowercase and we don't need to change the code of the Maven Enforcer plugin at all. :)
